version: "3"

tasks:
  test:
    desc: Run all tests
    cmds:
      - go test ./...

  bench:
    desc: Run benchmarks
    dir: benchmarks
    cmds:
      - go test -bench=. -benchmem -count=3

  bench:readme:
    desc: Run benchmarks and update README with results
    cmds:
      - ./scripts/update-benchmark-readme.sh
